env:
  global:
    - DISPLAY=":99.0"
notifications:
  recipients:
    - kou@cozmixng.org
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
before_script:
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
