markdown: kramdown
version: 2.1.8
release_date: 2015-09-06
rabbiter_version: 2.0.1
rabbiter_release_date: 2013-08-29
rabbirack_version: 2.0.0
rabbirack_release_date: 2012-08-29
rabwii_version: 2.0.0
rabwii_release_date: 2012-08-29
