markdown: rdiscount
pygments: true
version: 2.0.1
release_date: 2012-08-31
rabbiter_version: 2.0.0
rabbiter_release_date: 2012-08-29
rabbirack_version: 2.0.0
rabbirack_release_date: 2012-08-29
rabwii_version: 2.0.0
rabwii_release_date: 2012-08-29
